-- Создание DEV схемы
CREATE USER DEV_USER IDENTIFIED BY devpass DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE TO DEV_USER;

-- Создание PROD схемы
CREATE USER PROD_USER IDENTIFIED BY prodpass DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE TO PROD_USER;

SELECT username, account_status, created FROM dba_users
WHERE username IN ('DEV_USER', 'PROD_USER');
